version: "3.8"

services:
  angular:
    build: angular
    container_name: angular
    restart: always
    ports:
      - 4200:4200
    stdin_open: true
    volumes:
      - ./angular:/app
      - /app/node_modules
    networks:
      - angular-express
    depends_on:
      - nest

  nest:
    build: nest
    container_name: nest
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./nest:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - angular-express
    environment:
      STATUS: development
      PORT: 5000
      CORS: http://localhost:4200
      MONGODB: mongodb://mongo:27017/ArANM?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.1
      ATOKENSECRET: 439g73qp9g7btdco3684gvq038bvuav9q3-4hf80q3gbueorafbwuiafgbu9o243h80qfbn

  mongo:
    container_name: mongo
    restart: always
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  angular-express:
  express-mongo:
    
volumes:
  mongoDB: {}